package com.example.demorentalcar.model;


import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;

import static com.example.demorentalcar.constant.TableConstValue.*;

@NoArgsConstructor
@AllArgsConstructor
@Data
@Builder
@DynamoDBTable(tableName = USER_TABLE_NAME)
public class User {

    @DynamoDBHashKey(attributeName = USER_TABLE_ATTR_ID)
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBIndexHashKey(globalSecondaryIndexName = USER_TABLE_EMAIL_INDEX, attributeName = USER_TABLE_ATTR_EMAIL)
    private String email;

    @DynamoDBAttribute(attributeName = USER_TABLE_ATTR_FRIENDLY_NAME)
    private String friendlyName;

    @DynamoDBAttribute(attributeName = ATTR_CREATED_ON)
    private Date createdOn;

}
